### ISSUE TITLE
Is isJsonMime required in the Configuration object?

### ISSUE THREAD

**Issue by stevenwchien** [tremendous-rewards/tremendous-node#53]
The `isJsonMime` function isn't found in your API documentation anywhere. However, I'm finding that it is a required field in the `Configuration` type. When trying to build a `Configuration` object like so:

```typescript
    const tremendousConfiguration: TremendousConfiguration = {
        basePath: TremendousEnvironment.production,
        accessToken: TREMENDOUS_API_KEY,
    };
```

I am presented with the following Typescript error:
<img width="1094" alt="tremendous_api_type_error" src="https://github.com/tremendous-rewards/tremendous-node/assets/23484970/5eb84989-a059-435b-9c7e-9af0838137cb">

Peering into `configuration.d.ts` that comes with the package, I see:

```typescript
export declare class Configuration {
    /**
     * parameter for apiKey security
     * @param name security name
     * @memberof Configuration
     */
    apiKey?: string | Promise<string> | ((name: string) => string) | ((name: string) => Promise<string>);

    ....

    constructor(param?: ConfigurationParameters);
    /**
     * Check if the given MIME is a JSON MIME.
     * JSON MIME examples:
     *   application/json
     *   application/json; charset=UTF8
     *   APPLICATION/JSON
     *   application/vnd.company+json
     * @param mime - MIME (Multipurpose Internet Mail Extensions)
     * @return True if the given MIME is JSON, false otherwise.
     */
    isJsonMime(mime: string): boolean;
}
```

Wondering if this may have slipped into the OpenAPI spec generation by accident. Or if it is required, could you please add it to your documentation?

Thanks,
Steven Chien

**Comment by lucasmazza** [comment]
Hey @stevenwchien, have you tried building the config object using its constructor? That's the recommended way to initialize it before making requests with this SDK.

```ts
const tremendousConfiguration = new Configuration({
  basePath: TremendousEnvironment.production,
  accessToken: TREMENDOUS_API_KEY,
});
```

**Comment by stevenwchien** [comment]
@lucasmazza Thanks for the clarification. That works! I missed that in the docs
