### ISSUE TITLE
Incorrect return type for Order API getOrder

### ISSUE THREAD

**Issue by jo-warren** [tremendous-rewards/tremendous-node#82]
Calling `new Orders(config).getOrder()` returns an order object with a "rewards" property that's an array of rewards. However, the typing says the property is "reward" and is a single reward object. To be clear, this is an issue with the typescript generator.

**Comment by lucasmazza** [comment]
Hi @jo-warren. I believe the response body on our spec is wrong and we are working on fixing it, and for some reason our validation tasks didn't picked up this mismatch. Once we fix the spec we will release a new package with the correct types

**Comment by lucasmazza** [comment]
@jo-warren we fixed this on 2ce1785bfb71e3ff833911b3c752f2a81f93f499 and released `v3.5.0` with this change
