### ISSUE TITLE
Environments.Production returns the testflight url

### ISSUE THREAD

**Issue by jo-warren** [tremendous-rewards/tremendous-node#90]
Not sure if I'm misunderstanding something, but instantiating the client as per the docs
`
const configuration = new Configuration({
  basePath: Environments.production,
  accessToken: "YOUR-PRODUCTION-TOKEN",
});
`
is returning the testflight url instead of the prod url. I was able to just pass the prod url (https://www.tremendous.com/api/v2) as a string instead, but if that's the expected behavior, then I think the docs should indicate to just pass the actual url.

**Comment by jo-warren** [comment]
Actually, realized a typo - the Environments.production had the "p" capitalized. But suggestion for improvement would be maybe having the basePath accept an enum instead of a string.

**Comment by bzanchet** [comment]
Great. Also, if you could use https://api.tremendous.com instead, that should save you a few milliseconds every request.

That's the oficial production API URL.
